apiVersion: v2
name: home-assistant
description: A Helm chart for Home Assistant using lib-chart
type: application
version: 0.0.16
appVersion: "2026.4.0"
keywords:
  - home-assistant
  - home-automation
dependencies:
  - name: lib-chart
    alias: application
    version: "0.0.15"
    repository: "oci://ghcr.io/orhayoun-eevee"
maintainers:
  - name: Home Assistant Team
home: https://www.home-assistant.io/
